### ISSUE TITLE
MissingKotlinParameterException Plugin Crash when you open BPMN20.xml file 

### ISSUE THREAD

**Issue by chex123** [valb3r/flowable-bpmn-intellij-plugin#203]
**Describe the bug**
This plugin crashes with the stack-trace below when you try to open the sample bpmn20.xml file:
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.valb3r.bpmn.intellij.plugin.flowable.parser.nodes.process.SequenceFlow] value failed for JSON property id due to missing (therefore NULL) value for creator parameter id which is a non-nullable type
 at [Source: (StringReader); line: 8, column: 83] (through reference chain: com.valb3r.bpmn.intellij.plugin.flowable.parser.nodes.BpmnFile["process"]->java.util.ArrayList[0]->com.valb3r.bpmn.intellij.plugin.flowable.parser.nodes.ProcessNode["sequenceFlow"]->java.util.ArrayList[0]->com.valb3r.bpmn.intellij.plugin.flowable.parser.nodes.process.SequenceFlow["id"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:112)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.impl.MergingSettableBeanProperty.deserializeAndSet(MergingSettableBeanProperty.java:78)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:114)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3188)
	at com.valb3r.bpmn.intellij.plugin.flowable.parser.FlowableParser.parse(FlowableParser.kt:697)
	at com.valb3r.bpmn.intellij.plugin.core.CanvasBuilder.build(CanvasBuilder.kt:54)
	at com.valb3r.bpmn.intellij.plugin.BpmnPluginToolWindow.run(BpmnPluginToolWindow.kt:70)
	at com.valb3r.bpmn.intellij.plugin.flowable.actions.ViewFlowableBpmnDiagramAction$actionPerformed$1.run(ViewFlowableBpmnDiagramAction.kt:25)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$activateToolWindow$1.run(ToolWindowManagerImpl.kt:606)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**To Reproduce**
1. Right click your bpmn20.xml file
2. Click on 'view bpmn (flowable) diagram'
3. Check the bottom right hand corner of intelliJ 'IDE intenal error icon'

**BPMN definition**
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="Examples">
  
  <process id="signup-process" name="signup a new user">
    <startEvent id="start" flowable:initiator="initiator"/>
    <sequenceFlow sourceRef="start" targetRef="confirm-email-task"></sequenceFlow>
    <userTask id="confirm-email-task" name="confirm email" flowable:assignee="${initiator}"/>
    <sequenceFlow sourceRef="confirm-email-task" targetRef="send-welcome-email-task"/>
    <serviceTask id="send-welcome-email-task" flowable:expression= "#{emailService.sendWelcomeEmail(customerId, email)}"/>
    <sequenceFlow sourceRef="send-welcome-email-task" targetRef="end"/>
     <endEvent id="end"/>
     </process>
</definitions>

**Expected behavior**
The diagram editor for the bpmn20.xml file should open

**Screenshots**
![Screen Shot 2020-11-20 at 1 17 18 PM](https://user-images.githubusercontent.com/74789946/99853324-c3f62a80-2b50-11eb-85da-af72639fabc5.png)

**IntelliJ version (please complete the following information):**
 - Edition: Ultimate
 - Version 2020.2.3
 
**Additional context**
None

**Comment by valb3r** [comment]
@chex123 Can you please provide BPMN definition, or is it same as https://github.com/valb3r/flowable-bpmn-intellij-plugin/issues/203

**Comment by chex123** [comment]
> @chex123 Can you please provide BPMN definition, or is it same as #203

<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:flowable="http://flowable.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="Examples">
  
  <process id="signup-process" name="signup a new user">
    
    <startEvent id="start" flowable:initiator="initiator"/>
    
    <sequenceFlow sourceRef="start" targetRef="confirm-email-task"></sequenceFlow>
    
    <userTask id="confirm-email-task" name="confirm email" flowable:assignee="${initiator}"/>
    
    <sequenceFlow sourceRef="confirm-email-task" targetRef="send-welcome-email-task"/>
    
    <serviceTask id="send-welcome-email-task" flowable:expression= "#{emailService.sendWelcomeEmail(customerId, email)}"/>
    
    <sequenceFlow sourceRef="send-welcome-email-task" targetRef="end"/>
      
     <endEvent id="end"/>
     
     </process>
     
</definitions>

**Comment by chex123** [comment]
I think the issue might be that I do not have any DI (Diagram Tags) in the xml as you can see above. How do I automatically generate DI tags from an xml without any DI tags (xml with only bpmn process tags)

**Comment by valb3r** [comment]
The plugin relies heavily on the <diagram> and DI tags since it closely follows Flowable-modeler... 
It is an element auto-layout problem, that can be solved with PlantUML or GrapViz to some extent.
The auto-generated result will far away from ideal, but I think I can try to add diagram autogeneration to the plugin for such cases

**Comment by chex123** [comment]
Good day
Thanks for your reply and update. Yes a check in the plugin to auto
generate DI tags if they are not available in the xml file would be
super helpful

Please kindly let me know if its something you would be doing soon

Regards
Chex

**Comment by valb3r** [comment]
@chex123 No I don't think it will come soon, currently, the are more important features are on the plate, maybe in 3-4 months from now

**Comment by chex123** [comment]
Thank you for your response

In the mean time what way (or software) do you recommend I use to generate
the DI tags? Am still new to this technology

I appreciate your help
Regards
Chex

**Comment by valb3r** [comment]
1. You could try https://github.com/bpmn-io/bpmn-auto-layout
1. Or maybe this https://github.com/MarvinLudwig/bpmn_layouter in combination with https://github.com/camunda/camunda-modeler
1. But personally I would prefer creating diagram using some visual editor (like this plugin) as shown here: https://www.youtube.com/watch?v=pBfAGdp169s&feature=youtu.be or using bpmn.io online editor

**Comment by chex123** [comment]
Thanks a lot. Will try it out and let you know

Kind regards
Chex
