### ISSUE TITLE
Exception at startuup

### ISSUE THREAD

**Issue by kzmuhia** [valb3r/flowable-bpmn-intellij-plugin#217]
**Describe the bug**
When starting the IDE, exception due to slash in the path, but I am running linux so a leading will always be there

**To Reproduce**
Restart IDE

|
**Expected behavior**
No exception

**Screenshots**
Do not request resource from classloader using path with leading slash

com.intellij.diagnostic.PluginException: /icons/ui-icons/svg/exclusive-gateway.svg [Plugin: flowable-bpmn-visualizer]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:410)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:376)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.valb3r.bpmn.intellij.plugin.core.render.IconProviderKt.asResource(IconProvider.kt:79)
	at com.valb3r.bpmn.intellij.plugin.core.render.IconProviderKt.access$asResource(IconProvider.kt:1)
	at com.valb3r.bpmn.intellij.plugin.core.render.IconProviderImpl.<init>(IconProvider.kt:106)
	at com.valb3r.bpmn.intellij.plugin.core.render.IconProviderKt$currentIconProvider$1.apply(IconProvider.kt:72)
	at com.valb3r.bpmn.intellij.plugin.core.render.IconProviderKt$currentIconProvider$1.apply(IconProvider.kt)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
	at com.valb3r.bpmn.intellij.plugin.core.render.IconProviderKt.currentIconProvider(IconProvider.kt:70)
	at com.valb3r.bpmn.intellij.plugin.flowable.actions.NewFlowableBpmnAction.<init>(NewFlowableBpmnAction.kt:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:220)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:551)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1601)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:14)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**IntelliJ version (please complete the following information):**
 - Edition: Ultimate
 - Version 2021.1 Beta
 
**Additional context**

**Comment by valb3r** [comment]
@kzmuhia Thanks for the feedback, 
> Do not request resource from classloader using path with leading slash
probably it is not a slash issue 
https://plugins.jetbrains.com/docs/intellij/work-with-icons-and-images.html
states that all paths must start with a slash

I also use Linux and on 2020.3 everything seem to work fine. Will check the 2021.1 Beta

**Comment by valb3r** [comment]
@kzmuhia 
I've removed direct use of classloader in the hope it may help, as i.e. https://github.com/JetBrains/gradle-intellij-plugin/issues/425#issuecomment-524805655
https://github.com/valb3r/flowable-bpmn-intellij-plugin/commit/4a9bb3796cf949ee7064cd9f7694e052c161774e

Can you please test the plugin with this fix as I can't reproduce the issue on Ubuntu (I've built and attached files below, choose the plugin you use - install from file guide - https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk)
1. Activiti [activiti-bpmn-plugin.zip](https://github.com/valb3r/flowable-bpmn-intellij-plugin/files/6103471/activiti-bpmn-plugin.zip)
2. Flowable [flowable-bpmn-plugin.zip](https://github.com/valb3r/flowable-bpmn-intellij-plugin/files/6103474/flowable-bpmn-plugin.zip)

**Comment by kzmuhia** [comment]
with that installed the exception is gone, thanks for the speedy resolution.
