### ISSUE TITLE
KotlinNullPointerException

### ISSUE THREAD

**Issue by Mohicane** [valb3r/flowable-bpmn-intellij-plugin#225]
I just started with your plugin and want to use it with our activiti files.

But at the first usage, I have this exception:

> kotlin.KotlinNullPointerException
	at com.valb3r.bpmn.intellij.plugin.activiti.parser.ActivitiParser.toProcessObject(ActivitiParser.kt:636)
	at com.valb3r.bpmn.intellij.plugin.activiti.parser.ActivitiParser.parse(ActivitiParser.kt:149)
	at com.valb3r.bpmn.intellij.plugin.core.CanvasBuilder.build(CanvasBuilder.kt:52)
	at com.valb3r.bpmn.intellij.plugin.core.BpmnPluginToolWindow.run(BpmnPluginToolWindow.kt:82)
	at com.valb3r.bpmn.intellij.activiti.plugin.actions.ViewActivitiBpmnDiagramAction$actionPerformed$1.run(ViewActivitiBpmnDiagramAction.kt:25)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$activateToolWindow$1.run(ToolWindowManagerImpl.kt:632)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I work with IntellIJ 2021.1.1 Ultimate edition on a windows 10 laptop

**Comment by valb3r** [comment]
@Mohicane thanks for feedback, can you please provide sample file to reproduce the issue?

**Comment by Mohicane** [comment]
Yes for sure but it seems happening with every files we have.

Here an example:
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:activiti="http://activiti.org/bpmn"
             typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath"
             targetNamespace="http://www.jbpm.org/">

    <process id="pwf_archiving" name="pwf_archiving" isExecutable="true">
        <startEvent id="Start" name="Start"/>
        <sequenceFlow id="flow1" sourceRef="Start" targetRef="ReadyToArchive"/>
        <userTask id="ReadyToArchive" name="ReadyToArchive" activiti:assignee="parapheur"/>
        <sequenceFlow id="flow2" sourceRef="ReadyToArchive" targetRef="Archived"/>
        <endEvent id="Archived" name="Archived"/>
    </process>
</definitions>`

**Comment by valb3r** [comment]
@Mohicane Do your BPMN files include `<diagrams>` section? As it is mandatory for this plugin

**Comment by Mohicane** [comment]
Ok....

I missunderstood the usage of this plugin. I thought it creates on the fly diagrams.

Sorry. Then no problem with your plugin.

**Comment by wangjiaxong** [comment]
whow to auto generat diagrams <bpmndi:BPMNDiagram> section,I don't know how to set <omgdi:waypoint x="129.94999943586103" y="178.0"></omgdi:waypoint>
