### ISSUE TITLE
Supported extensions parameter doesn't work on IntelliJ 2022.3

### ISSUE THREAD

**Issue by mathieuLEM** [valb3r/flowable-bpmn-intellij-plugin#331]
Setting / Tools / Activiti BPMN plugin config ==> "Supported extensions(comma-separated)" parameter is set from "bpmn20.xml" to "bpmn20.xml,bpmn", but it's impossible to apply this change, the button doesnt' work (and the same if you directly put "OK", it's not applicated)

**Comment by valb3r** [comment]
@mathieuLEM Please provide IntelliJ version details - `About IntelliJ IDEA` tab.
For example:
```
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Licensed to Valentyn Berezin
Subscription is active until December 30, 2022.
Runtime version: 17.0.5+1-b653.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
    org.antlr.intellij.plugin (1.19.3-3)
    org.intellij.plugins.hcl (223.7571.175)
    org.jetbrains.plugins.go-template (223.7571.203)
    com.intellij.kubernetes (223.7571.175)
    YourKit Java Profiler 2022.3-b106 Integration (2022.3.106.0)
    PlantUML integration (5.20)
    flowable-bpmn-visualizer (0.5.0)
    org.asciidoctor.intellij.asciidoc (0.38.4)
    Pythonid (223.7571.182)

Kotlin: 223-1.7.20-release-201-IJ7571.182
```

**Comment by mathieuLEM** [comment]
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    activiti-bpmn-visualizer (0.5.0)

Kotlin: 223-1.7.21-release-272-IJ8214.52

**Comment by Trishun** [comment]
Hi. Same here. Params very simmilar to @mathieuLEM apart from:
```
Linux 5.15.0-56-generic
Memory: 1986M
Current Desktop: ubuntu:GNOME
```

**Comment by Trishun** [comment]
Some more info:
- changing `Supported extensions` is the only action not activating `Apply` button
- none of settings works
- first `OK` ended with exception [1]
- `Apply` press ends with warning [2]

[1]
```
2023-01-04 11:35:10,336 [  22486]   WARN - #c.i.o.o.n.SettingsTreeView$MyBuilder - 'AbstractTreeBuilder' is going to be dropped soon and must not be used                                                                                                                                                                                      
com.intellij.diagnostic.PluginException: 'AbstractTreeBuilder' is going to be dropped soon and must not be used                                                                                                                                                                                                                                
        at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)                                                                                                                                                                                                                   
        at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)                                                                                                                                                                                                                                                      
        at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:60)                                                                                                                                                                                                                                              
        at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:55)                                                                                                                                                                                                                                              
        at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:47)                                                                                                                                                                                                                                              
        at com.intellij.ui.treeStructure.filtered.FilteringTreeBuilder.<init>(FilteringTreeBuilder.java:46)                                                                                                                                                                                                                                    
        at com.intellij.openapi.options.newEditor.SettingsTreeView$MyBuilder.<init>(SettingsTreeView.java:931)                                                                                                                                                                                                                                 
        at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:174)                                                                                                                                                                                                                                           
        at com.intellij.openapi.options.newEditor.SettingsDialog.treeViewFactory(SettingsDialog.java:89)                                                                                                                                                                                                                                       
        at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:194)
        at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:65)
        at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.java:38)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.getDialog(ShowSettingsUtilImpl.java:39)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
        at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
        at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
        at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-01-04 11:35:16,151 [  28301]   WARN - #c.i.u.x.Binding - no accessors for org.jetbrains.idea.perforce.perforce.ConnectionId
```

[2] `2023-01-04 11:35:46,216 [  58366]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting`
