### ISSUE TITLE
plugin version 0.5.1 can't use in idea 2023.3.2 Ultimate edition

### ISSUE THREAD

**Issue by ClockworkChen** [valb3r/flowable-bpmn-intellij-plugin#337]
can't use in idea 2023.3.2

**To Reproduce**
after finish to install the plugin,it will open an blank window,and then throw an exception.
kotlin.KotlinNullPointerException
	at com.valb3r.bpmn.intellij.plugin.core.events.ProcessModelUpdateEventsKt.updateEventsRegistry(ProcessModelUpdateEvents.kt:24)
	at com.valb3r.bpmn.intellij.plugin.core.state.CurrentStateProvider.handleUpdates(CurrentState.kt:95)
	at com.valb3r.bpmn.intellij.plugin.core.state.CurrentStateProvider.currentState(CurrentState.kt:83)
	at com.valb3r.bpmn.intellij.plugin.core.render.Canvas.updatePropertyVisualizer(Canvas.kt:426)
	at com.valb3r.bpmn.intellij.plugin.core.render.Canvas.click(Canvas.kt:211)
	at com.valb3r.bpmn.intellij.plugin.core.MouseEventHandler.mouseClicked(MouseEventHandler.kt:39)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**BPMN definition**

**Expected behavior**
plugin can't to use.

**Screenshots**
![无标题](https://user-images.githubusercontent.com/842274/221329475-d821ca8c-38b9-4081-8d02-b727a9f7eb79.png)

**IntelliJ version (please complete the following information):**
 - Plugin version: 0.5.1
 - Version [IntelliJ IDEA 2022.3.2 (Ultimate Edition)]

**Comment by valb3r** [comment]
@ClockworkChen Thanks for feedback. You can safely ignore the message for now. Just hide the plugin window by clicking `BPMN-Flowable-Diagram`. 
The bug is going to be fixed sometime later

**Comment by valb3r** [comment]
Fixed: 0faf44b
