### ISSUE TITLE
Exception in plugin Activiti BPMN visualizer (0.5.2)

### ISSUE THREAD

**Issue by malcolmlangillecgi** [valb3r/flowable-bpmn-intellij-plugin#350]
**Describe the bug**
The popup context menu does not show up

**To Reproduce**
1. Exception is thrown

**BPMN definition**

na

**Expected behavior**
Menu option is visible

**Screenshots**
kotlin.KotlinNullPointerException
	at com.valb3r.bpmn.intellij.plugin.core.ui.components.popupmenu.CanvasPopupMenuProviderKt.popupMenuProvider(CanvasPopupMenuProvider.kt:17)
	at com.valb3r.bpmn.intellij.plugin.core.MouseEventHandler.mouseClicked(MouseEventHandler.kt:32)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6659)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**IntelliJ version (please complete the following information):**
 - Edition: IntelliJ IDEA 2023.1.2 (Ultimate Edition)
 - Version Build #IU-231.9011.34, built on May 16, 2023
 
**Additional context**
na

**Comment by valb3r** [comment]
@malcolmlangillecgi Thanks for feedback, this looks like a bug.

Have you created new or opened existing diagram before clicking for menu?

**Comment by malcolmlangillecgi** [comment]
Yes the Camunda version works fine but not the Activity version of the
plugin.

I can't get the contextual menu to come up for any of my diagrams if I'm
using the Activity version of the plugin.

Malcolm

**Comment by valb3r** [comment]
@malcolmlangillecgi That's very weird, as 2 plugins use almost the same flows. Can you please provide a video showing your actions with Activiti, since I can't really reproduce the issue

**Comment by valb3r** [comment]
@malcolmlangillecgi Activiti plugin uses `bpmn20.xml` extension by default (this is the extension assigned by Activiti modeler 6.x). 
To be able to open your diagrams (`.bpmn`) in Activiti plugin see:
[Add bpmn extension to Activiti](https://github.com/valb3r/flowable-bpmn-intellij-plugin#q-my-files-for-activitiflowable-engine-have-bpmn-extension-and-not-bpmn20xml-how-can-i-open-them)
