### ISSUE TITLE
Fatal error after updating to 0.5.3

### ISSUE THREAD

**Issue by ideaplugins** [valb3r/flowable-bpmn-intellij-plugin#364]
After the update to version 0.5.3 on Idea 2023.2 beta I got this error and Idea did not start

```
Start Failed
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.diagnostic.PluginException: Key com.valb3r.bpmn.intellij.plugin.core.advertisement.AdvertisementState duplicated; existingAdapter: ServiceAdapter(descriptor=ServiceDescriptor(interface='null', serviceImplementation='com.valb3r.bpmn.intellij.plugin.core.advertisement.AdvertisementState', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=Activiti BPMN visualizer, id=activiti-bpmn-visualizer, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2023.2/activiti-bpmn-plugin, version=0.5.3, package=null, isBundled=false)); descriptor=com.valb3r.bpmn.intellij.plugin.core.advertisement.AdvertisementState,  app=Application (containerState PRE_INIT) , current plugin=camunda-bpmn-visualizer
	at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:566)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:257)
	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:48)
	at com.intellij.ide.bootstrap.AppPreInitKt$initServiceContainer$2.invokeSuspend(appPreInit.kt:41)
	at com.intellij.ide.bootstrap.AppPreInitKt$initServiceContainer$2.invoke(appPreInit.kt)
	at com.intellij.ide.bootstrap.AppPreInitKt$initServiceContainer$2.invoke(appPreInit.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.diagnostic.TracerKt.subtask(tracer.kt:45)
	at com.intellij.diagnostic.TracerKt.subtask$default(tracer.kt:34)
	at com.intellij.ide.bootstrap.AppPreInitKt.initServiceContainer(appPreInit.kt:40)
	at com.intellij.ide.bootstrap.AppPreInitKt$initServiceContainer$1.invokeSuspend(appPreInit.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by valb3r** [comment]
@ideaplugins Unfortunately, you would need to delete one of them manually. 
If you use JetBrains toolbox - here is the video how to do that:

https://github.com/valb3r/flowable-bpmn-intellij-plugin/assets/18463491/5ef8fc0e-8030-46f7-88b2-c81e46799a93

You need to open IJ Settings. Go to its `Install location`, open `plugins` directory and remove it there

**Comment by valb3r** [comment]
I've removed release 0.5.3 from Marketplace as probably you are not one who can have such setup. The issue will be fixed in 0.5.3.1

**Comment by valb3r** [comment]
If you are not using JetBrains toolbox, then you would need to find `plugins` folder by following this guide:
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by ideaplugins** [comment]
thanks, I had already removed it manually before I submitted the ticket :+1:

**Comment by valb3r** [comment]
Fixed in 0.5.3.1
