### ISSUE TITLE
NPE on ID update then name update

### ISSUE THREAD

**Issue by valb3r** [valb3r/flowable-bpmn-intellij-plugin#37]
**Describe the bug**
When ID is updated and element name afterwards NPE seem to happen occasionally.

**To Reproduce**
```
kotlin.TypeCastException: null cannot be cast to non-null type org.w3c.dom.Element
	at com.valb3r.bpmn.intellij.plugin.flowable.parser.FlowableParser.applyPropertyUpdateWithId(FlowableParser.kt:310)
	at com.valb3r.bpmn.intellij.plugin.flowable.parser.FlowableParser.doUpdate(FlowableParser.kt:133)
	at com.valb3r.bpmn.intellij.plugin.flowable.parser.FlowableParser.parseAndWrite(FlowableParser.kt:115)
	at com.valb3r.bpmn.intellij.plugin.flowable.parser.FlowableParser.update(FlowableParser.kt:98)
	at com.valb3r.bpmn.intellij.plugin.events.ProcessModelUpdateEvents.commitToFile(ProcessModelUpdateEvents.kt:62)
	at com.valb3r.bpmn.intellij.plugin.events.ProcessModelUpdateEvents.addPropertyUpdateEvent(ProcessModelUpdateEvents.kt:87)
	at com.valb3r.bpmn.intellij.plugin.properties.PropertiesVisualizer$buildTextField$1.invoke(PropertiesVisualizer.kt:67)
	at com.valb3r.bpmn.intellij.plugin.properties.PropertiesVisualizer$buildTextField$1.invoke(PropertiesVisualizer.kt:17)
	at com.valb3r.bpmn.intellij.plugin.properties.PropertiesVisualizer.clear(PropertiesVisualizer.kt:24)
	at com.valb3r.bpmn.intellij.plugin.render.Canvas.click(Canvas.kt:84)
	at com.valb3r.bpmn.intellij.plugin.MouseEventHandler.mouseClicked(MouseEventHandler.kt:23)
	at java.awt.Component.processMouseEvent(Component.java:6553)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by valb3r** [comment]
Fixed by 
https://github.com/valb3r/flowable-bpmn-intellij-plugin/commit/213a642425f21fdf086b98f957a99995dbef84b6
