### ISSUE TITLE
Activiti BPMN visualizer crashes while opening BPMN file in Community edition

### ISSUE THREAD

**Issue by thomasulllrich** [valb3r/flowable-bpmn-intellij-plugin#373]
Hi!
I installed the Activiti BPMN visualizer in Intellij Idea Community edition (IntelliJ IDEA 2023.2 (Community Edition) Build #IC-232.8660.185, built on July 26, 2023
) and got this error:

`com.google.common.util.concurrent.UncheckedExecutionException: com.intellij.diagnostic.PluginException: Cannot load class com.valb3r.bpmn.intellij.plugin.core.render.CanvasPainter$BufferedImageTranscoder (
  error: org/apache/batik/transcoder/image/ImageTranscoder,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Activiti BPMN visualizer, id=activiti-bpmn-visualizer, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2023.2\plugins\activiti-bpmn-plugin, version=0.5.4, package=null, isBundled=false), packagePrefix=null, state=active)
)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at com.valb3r.bpmn.intellij.plugin.core.render.CanvasPainter.rasterizeSvg(CanvasPainter.kt:594)
	at com.valb3r.bpmn.intellij.plugin.core.render.CanvasPainter.drawWrappedIconWithLayer(CanvasPainter.kt:378)
	at com.valb3r.bpmn.intellij.plugin.core.render.elements.shapes.EllipticIconOnLayerShape.doRender(EllipticIconOnLayerShape.kt:28)
	at com.valb3r.bpmn.intellij.plugin.core.render.elements.shapes.ShapeRenderElement.doRenderWithoutChildren(ShapeRenderElement.kt:74)
	at com.valb3r.bpmn.intellij.plugin.core.render.elements.BaseDiagramRenderElement.render(BaseDiagramRenderElement.kt:90)
	at com.valb3r.bpmn.intellij.plugin.core.render.elements.BaseDiagramRenderElement.render(BaseDiagramRenderElement.kt:91)
	at com.valb3r.bpmn.intellij.plugin.core.render.DefaultBpmnProcessRenderer.doRender(DefaultBpmnProcessRenderer.kt:124)
	at com.valb3r.bpmn.intellij.plugin.core.render.DefaultBpmnProcessRenderer.doRender$default(DefaultBpmnProcessRenderer.kt:106)
	at com.valb3r.bpmn.intellij.plugin.core.render.DefaultBpmnProcessRenderer.render(DefaultBpmnProcessRenderer.kt:99)
	at com.valb3r.bpmn.intellij.plugin.core.render.Canvas$paintComponent$1.invoke(Canvas.kt:127)
	at com.valb3r.bpmn.intellij.plugin.core.render.Canvas$paintComponent$1.invoke(Canvas.kt:120)
	at com.valb3r.bpmn.intellij.plugin.core.render.Canvas.withFps(Canvas.kt:684)
	at com.valb3r.bpmn.intellij.plugin.core.render.Canvas.paintComponent(Canvas.kt:120)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5312)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5260)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5070)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:400)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class com.valb3r.bpmn.intellij.plugin.core.render.CanvasPainter$BufferedImageTranscoder (
  error: org/apache/batik/transcoder/image/ImageTranscoder,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Activiti BPMN visualizer, id=activiti-bpmn-visualizer, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2023.2\plugins\activiti-bpmn-plugin, version=0.5.4, package=null, isBundled=false), packagePrefix=null, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:331)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:178)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.valb3r.bpmn.intellij.plugin.core.render.CanvasPainter.rasterizeSvg$lambda$5(CanvasPainter.kt:596)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 61 more
Caused by: java.lang.NoClassDefFoundError: org/apache/batik/transcoder/image/ImageTranscoder
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:268)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:113)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:238)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:188)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:326)
	... 70 more
Caused by: java.lang.ClassNotFoundException: org.apache.batik.transcoder.image.ImageTranscoder PluginClassLoader(plugin=PluginDescriptor(name=Activiti BPMN visualizer, id=activiti-bpmn-visualizer, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2023.2\plugins\activiti-bpmn-plugin, version=0.5.4, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 78 more
`

BR,
Thomas

**Comment by valb3r** [comment]
Fixed in: https://github.com/valb3r/flowable-bpmn-intellij-plugin/commit/734692a4210ccf2771a51e1e1394f0a811b0c06e

Pending release
